// Generated by https://quicktype.io

export interface User {
    id:                number;
    name:              string;
    email:             string;
    email_verified_at: string;
    created_at:        string;
    updated_at:        string;
    fecha_nacimiento:  string;
    edad:              number;
    domicilios:        Domicilio[];
}

export interface Domicilio {
    id:              number;
    user_id:         number;
    domicilio:       string;
    numero_exterior: string;
    colonia:         string;
    codigo_postal:   string;
    ciudad:          string;
    created_at:      string;
    updated_at:      string;
}
